/**
 * @description       : NicepayAdapter
 * @author            : sungho.jo@mz.co.kr
 * @group             : MegazoneCloud
 * @last modified on  : 2024-03-20
 * @last modified by  : sungho.jo@mz.co.kr
**/
global class NicepayAdapter implements commercepayments.PaymentGatewayAdapter{
    global commercepayments.GatewayResponse processRequest(commercepayments.PaymentGatewayContext pgContext){
        commercepayments.GatewayResponse response = null;
        return response;
    }
}