/**
 * @description       : NotificationSetHandler 
 *                      값을 매뉴얼 처리시 notificaiton을 설정하기 위한 virtual class
 *                      sample class : NotificationSetHandler_T0002
 * @author            : sungho.jo@mz.co.kr
 * @group             : MegazoneCloud
 * @last modified on  : 2024-03-14
 * @last modified by  : sungho.jo@mz.co.kr
**/
public virtual class NotificationSetHandler {
    
    /**
    * @description notification 재설정
    * @author sungho.jo@mz.co.kr | 2024-03-13 
    * @param notiObj : Notification
    **/
    public virtual void setNotification(Notification notiObj){}
}